# Generated by Django 2.1.7 on 2019-06-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choise',
            new_name='Choice',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='question_text',
            new_name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='questioner_text',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
