# Generated by Django 2.1.7 on 2019-06-16 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190610_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questioner_text',
        ),
    ]
